package ai.tabforge.telegramclaw.relay;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.concurrent.ConcurrentHashMap;

/**
 * Manages short-lived pairing PINs that let new Telegram users self-authorize at runtime.
 *
 * <p>Analogy: like a time-limited visitor badge system — the device owner (Android app)
 * generates a badge code (PIN) and hands it to the visitor out-of-band (WhatsApp, in person).
 * The visitor presents it in Telegram; if valid and not expired, they are permanently added
 * to the authorized set. Each PIN is single-use and expires in 10 minutes.</p>
 *
 * <p>Protocol 6 (Out-of-Band Pairing): pairing is always initiated by the device owner,
 * so no unauthorized user can gain access without the owner's explicit action.</p>
 *
 * <p>Called by: {@link PairHandler} (to register a new PIN received from the Android app)
 * and {@link TelegramUpdateReceiver} (to validate a PIN submitted via Telegram message).</p>
 */
public class PairingService {

    private static final Logger log = LoggerFactory.getLogger(PairingService.class);
    private static final long PIN_TTL_MS = 10 * 60 * 1000L;

    private final ConcurrentHashMap<String, Long> pendingPins = new ConcurrentHashMap<>();
    private final AuthorizationService authorizationService;

    public PairingService(AuthorizationService authorizationService) {
        this.authorizationService = authorizationService;
    }

    /**
     * Registers a PIN generated by the Android app. If the same PIN is submitted again,
     * its expiry is refreshed. Stored uppercase regardless of input case.
     *
     * <p>Called by: {@link PairHandler} when Android POSTs to /pair.</p>
     *
     * @param pin  6-character alphanumeric PIN (any case)
     */
    public void registerPin(String pin) {
        String upper = pin.toUpperCase();
        long expiry = System.currentTimeMillis() + PIN_TTL_MS;
        pendingPins.put(upper, expiry);
        log.info("[PAIR] PIN registered — valid for 10 min.");
    }

    /**
     * Validates a PIN submitted by an unauthorized Telegram user. On success, permanently
     * authorizes them and consumes the PIN so it cannot be reused.
     *
     * <p>Called by: {@link TelegramUpdateReceiver#handleMessage} before the auth rejection.</p>
     *
     * @param chatId      Telegram user ID of the sender attempting to pair
     * @param senderName  display name of the sender (for logging)
     * @param pin         the 6-character string the sender typed
     * @return true if the PIN was valid and the user is now authorized; false otherwise
     */
    public boolean attemptPair(long chatId, String senderName, String pin) {
        String upper = pin.toUpperCase();
        Long expiry = pendingPins.get(upper);

        if (expiry == null) {
            log.debug("[PAIR] PIN '{}' not found.", upper);
            return false;
        }
        if (System.currentTimeMillis() > expiry) {
            pendingPins.remove(upper);
            log.info("[PAIR] PIN '{}' expired — rejected.", upper);
            return false;
        }

        pendingPins.remove(upper); // single-use
        authorizationService.addAuthorizedId(chatId, senderName);
        log.info("[PAIR] {} (id={}) paired successfully via PIN.", senderName, chatId);
        return true;
    }
}
